### ISSUE TITLE
Umbrella issue for tracking work on connecting to backing services

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1262]
We need to define how to bind a function to a backing service that have been created using service catalog, helm or even manually

List of issues:

- [ ] Enable CLI to define a volume mount for secrets/configMaps https://github.com/projectriff/cli/issues/57
- [ ] document configuration needed for service catalog use with riff #1259 
- [ ] define function bindings needed to use service created via service catalog #1260 
- [ ] define a CRD to be used when binding a backing service to a function #1261
