### ISSUE TITLE
Release riff v0.4.0

### ISSUE THREAD

**Issue by scothis** [projectriff/riff#1350]
### phase 1

- [x] projectriff/fats
  - [x] create a v0.4.x branch from master
  - that's it
- [x] projectriff/command-function-invoker
  - nothing to do
- [x] projectriff/command-function-buildpack
  - [x] remove `-BUILD-SNAPSHOT` from version in buildpack.toml
  - [x] commit, push to master, wait for CI to go green
  - [x] tag as v0.0.9, push
  - [x] bump version number, restoring `-BUILD-SNAPSHOT` push to master
- [x] projectriff/java-function-invoker
  - nothing to do
- [x] projectriff/java-function-buildpack
  - [x] remove `-BUILD-SNAPSHOT` from version in buildpack.toml
  - [x] commit, push to master, wait for CI to go green
  - [x] tag as v0.1.5, push
  - [x] bump version number, restoring `-BUILD-SNAPSHOT` push to master
- [x] projectriff/node-function-invoker
  - [x] change version in package.json to drop `-snapshot`
  - [x] `npm i && npm t` # updates the shrinkwrap
  - [x] commit, push to master, wait for CI to go green
  - [x] tag as v0.1.2, push
  - [x] check that CI pushed a build to npm https://www.npmjs.com/package/@projectriff/node-function-invoker
- [x] projectriff/node-function-buildpack
  - [x] update riff-invoker-node dependency in buildpack.toml to consume v0.1.2
  - [x] commit, push to master, wait for CI to go green
  - [x] remove `-BUILD-SNAPSHOT` from version in buildpack.toml
  - [x] commit, push to master, wait for CI to go green
  - [x] tag as v0.1.1, push
  - [x] bump version number, restoring `-BUILD-SNAPSHOT` push to master

### phase 2

- [x] projectriff/builder
  - [x] create a v0.4.x release branch
  - [x] update builder.toml.tpl to consume releases instead of snapshots for each invoker, run `make template`
  - [x] update fats refspec to consume v0.4.x
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] update VERSION file to remove `-snapshot`
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] tag as v0.4.0, push
  - [x] bump VERSION on v0.4.x branch to 0.4.1-snapshot, push to v0.4.x
  - [x] bump VERSION on master branch to 0.5.0-snapshot, push to master
- [x] projectriff/system
  - [x] create a v0.4.x release branch
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] update VERSION file to remove `-snapshot`
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] tag as v0.4.0, push
  - [x] bump VERSION on v0.4.x branch to 0.4.1-snapshot, push to v0.4.x
  - [x] bump VERSION on master branch to 0.5.0-snapshot, push to master

### phase 3

- [x] projectriff/charts
  - [x] create a v0.4.x release branch
  - [x] update fats refspec to consume v0.4.x
  - [x] update template.yaml.tpl to consume releases from the v0.4.x branch for system and the build templates
  - [x] run `make templates`
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] update VERSION file to remove `-snapshot`
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] tag as v0.4.0, push
  - [x] bump VERSION on v0.4.x branch to 0.4.1-snapshot, push to v0.4.x
  - [x] bump VERSION on master branch to 0.5.0-snapshot, push to master

### phase 4

- [x] projectriff/cli
  - [x] create a v0.4.x release branch
  - [x] update fats refspec to consume v0.4.x
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] update VERSION file to remove `-snapshot`
  - [x] commit, push to v0.4.x, wait for CI to go green
  - [x] tag as v0.4.0, push
  - [x] bump VERSION on v0.4.x branch to 0.4.1-snapshot, push to v0.4.x
  - [x] bump VERSION on master branch to 0.5.0-snapshot, push to master

### phase 5

- [x] smoke test release artifacts
  - [x] install helm charts from the chart repo without `--devel`
  - [x] use release build of the CLI
- [x] github releases
  - [x] create releases on github for v0.4.0 tag in cli repo
  - [x] add CLI binaries from GCS, do not rebuild from source
  - [x] ~other repos???~
- [x] submit [PR](https://github.com/Homebrew/homebrew-core/pull/43189) to update homebrew
- [x] [projectriff/chocolatey](https://chocolatey.org/packages/riff/0.4.0)
  - [x] consume 0.4.0 cli
  - [x] [commit, push to master](https://github.com/projectriff/chocolatey/commit/50ea848329592be50b58a20865ebdc76fbb51a98)
  - [x] test locally (see repo [instructions](https://github.com/projectriff/chocolatey/))
  - [x] run publish script
- [x] projectriff/projectriff.io
  - [x] merge https://github.com/projectriff/projectriff.io/pull/91
  - [x] create a release announcement blog post
  - [x] make the new site live on projectriff.io
- [x] close milestone v0.4.0 in each repo
  - [x] move open issues into v0.5.0

### phase 6

- [x] 🍻🎉

**Comment by scothis** [comment]
All of the release artifacts are tased and staged with 🍏 CI. Ready for manual smoke testing.

**Comment by fbiville** [comment]
Waiting for Homebrew merge.
Chocolatey update is being verified and should be approved within the next hours, hopefully.
