### ISSUE TITLE
Broker pluggability

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#220]
Umbrella issue to spike broker pluggability
Per discussion post S1P

### message transports
- redis streams - see http://antirez.com/news/114
- rabbimq

### monitoring for scaling
- non-kafka-specific replacement for input-topic offset monitoring 
- idea is to monitor with info from gateway / sidecars - envoy-style load detection
- implies ambassador sidecar for message ingress
- NOTE: also need to monitor function outputs for functions that don't depend on input load

**Comment by glyn** [comment]
@jldec I think the description of this issue should actually say:

- [ ] publish function scaling metrics from gateway
- [ ] [publish function scaling metrics from sidecar](https://github.com/projectriff/function-sidecar/issues/41)
- [ ] [subscribe to function scaling metrics from function-controller](https://github.com/projectriff/function-controller/issues/7)
- [ ] ...

**Comment by ericbottard** [comment]
While I agree the original wording can be made more descriptive, I don't think trying to break it down like that is a good idea.
First of all, all `Producer` and `Consumer` should be decorated to emit metrics. Thus, there is no distinction to be made between the gateway and other emitting parts of the system. Let's not forget other sources (than the gw) could exist in the system
Then, while I understand the intention, those are not "scaling metrics" they're just "(rate) metrics" until something (the controller) decides to use them to do scaling. This is important because this may bias the solution towards something that may not be portable across brokers.
Lastly, we don't subscribe to those metrics *from* the function-controller, but really *at* the function-controller (ie the controller is not emitting, but I see how "from" could be ambiguous)

So really, if I were to come up with two bullets, I'd actually loosen Jurgen's wording
- publish metrics from producers/consumers (that can be the sidecar OR the gw)
- subscribe to metrics at the function-controller and drive scaling instructions from them

Just my $.02

**Comment by glyn** [comment]
Yes, that's clearer. Thanks.

**Comment by markfisher** [comment]
Well said Eric! I would add that we might want to consider either re-using the Function Sidecar as an "ambassador" within the HTTP Gateway pod (see Example 2 here: http://blog.kubernetes.io/2015/06/the-distributed-system-toolkit-patterns.html), or at least factoring out common code into a library so that the Producer for HTTP Gateway is essentially the same as the Producer for the Sidecar's output events. Ultimately the gateway might evolve to include some relationship with an Ingress Controller and/or Istio/Envoy, but we probably can avoid that distraction while still making some useful progress with DRY refactoring.

**Comment by ericbottard** [comment]
> at least factoring out common code into a library so that the Producer for HTTP Gateway is essentially the same as the Producer for the Sidecar's output events

That's already exactly what we have I would argue: the `http-gateway` is re-using `message-transport`

**Comment by markfisher** [comment]
...but I guess the decorator that adds metrics-emitting shouldn't be too tightly coupled to the core `message-transport` responsibility (but that might already be recognized also)

**Comment by jldec** [comment]
updated original post (OP) above

**Comment by glyn** [comment]
Updated OP to say "... scaling from the function controller" rather than "... scaling from the function invoker".
