### ISSUE TITLE
riff release v0.1.1

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#646]
### v0.1.1 plan

- [x] handle ingress hostnames in addition to IPs #632
- [x] riff system install and uninstall with or without Istio #633 
- [x] escape arguments to curl in service invoke #641 
- [x] make cli go get'able #638
- [x] env var support for services #647
- [x] restore command invoker #643 
- [x] publish and point CLI to latest install yaml for Istio, Knative, eventing, bus 
### cut the release
  - [x] set VERSION to 0.1.1
  - [x] validate CI, smoke test
  - [x] tag release
  - [x] create release page with install instructions for CLI and upload binaries
  - [x] bump VERSION to 0.1.2-snapshot
  - [x] merge blog post

**Comment by markfisher** [comment]
we should also include CLI support for the command invoker

**Comment by trisberg** [comment]
do we need new invoker releases? I assume we would need a command invoker release if we were to include it.

**Comment by markfisher** [comment]
yes we would at least need a new release of the command invoker since HTTP support was added

**Comment by scothis** [comment]
> we should also include CLI support for the command invoker

Once CLI support is added, we can also add support in FATS
