### ISSUE TITLE
Getting started guides

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#655]
The getting started docs for riff v0.1.0 were mostly about installation and then creating a single javascript function.  This issue proposes a series of additional getting started docs to illustrate significant features of riff on Knative. Some of these may end up in Knative docs or samples. 

### serving
- [ ] function autoscaling 0-1, 1-N, back down to 0
- [ ] function revisions with incremental routing (using riff cli to create / update the function)

### eventing
- [ ] pub/sub: 2 subscriptions to apps/functions over single channel 
- [ ] feed internal k8s events source to app/function 
- [ ] feed external GitHub webhook source to app/function

### buses
- [ ] Kafka
- [ ] GCP PubSub

### function invokers
- [ ] node function with dependencies
- [ ] java function
- [ ] command function

### apps
- [ ] java boot app

**Comment by scothis** [comment]
stale
