### ISSUE TITLE
riff CLI roadmap

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#656]
The cli riff v0.1.0 makes it possible to work with functions and services on Knative and connect them over channels, all without requiring users to work directly with yaml. It also simplifies Knative system install.

This issue proposes a roadmap for additional CLI features to perform common operations on Knative.

### install and uninstall
- [x] riff system uninstall #625 
- [x] separate istio install/uninstall #633 

### builds
- [ ] use buildpack build template
- [ ] verbose mode for function create #623 
- [ ] trigger new function build, create revision #671

### channels and subscriptions
- [ ] bus params #620 
- [ ] output chaining #672
 
### other
- [ ] buses #624
- [ ] routes and configurations #619

**Comment by scothis** [comment]
stale
