### ISSUE TITLE
Knative eventing roadmap for riff

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#657]
This issue outlines key enhancements to knative/eventing for riff. 

The short term goal is to achieve parity with pre-Knative riff in terms of being able to connect functions over channels. The long term goal is to enable Knative as a platform for event stream processing.

### event traffic
- [ ] response chaining - https://github.com/knative/eventing/issues/216
- [ ] ingress/gateway for directing external event to channels
- [ ] simple HTTP event output wiring

###  streaming
- [ ] non HTTP protocol support e.g. gRPC
- [ ] separate event streams for input and ouput
- [ ] windowing support

### buses
- [ ] document configuration - https://github.com/knative/eventing/issues/282
- [ ] report channel and subscription status - https://github.com/knative/eventing/issues/285
- [ ] move to separate repos - https://github.com/knative/eventing/issues/289
- [ ] redis bus

**Comment by scothis** [comment]
Our roadmap for Knative Eventing is not to use Knative Eventing.
