### ISSUE TITLE
Observability roadmap

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#674]
Users of riff on Knative need ways to see what's going on, especially when things don't work as expected. This includes feedback during long operations like builds and installs, access to services for retrieving or searching logs and capturing of performance metrics and tracing.

### k8s / Knative 
- [ ] improve visbility of delays caused by container image pulls

### install
- [ ] riff system install manifest option to make it possible to include tracing and monitoring #648 
- [ ] riff system install option to include elastic/kibana - this can be handled by using full `release-yaml` in a manifest
 
### build
- [x] verbose build output during function create #623

### runtime
- [ ] syslog target for logs

**Comment by scothis** [comment]
stale
