### ISSUE TITLE
Invoker Roadmap

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#675]
Riff v0.1.0 included support for Java and Node invokers, and v0.1.1 added the command invoker. All of these are currently limited to handling single-event-at-a-time requests over HTTP. 

Our plans for the immediate future include invoker extensibilty #634 and buildpacks #654. 

### Languages
- [x] [Java](https://github.com/projectriff/java-function-invoker)
- [x] [Node](https://github.com/projectriff/node-function-invoker)
- [x] [Command](https://github.com/projectriff/command-function-invoker)
- [ ] [Python3](https://github.com/projectriff/python3-function-invoker)
- [ ] [Go](https://github.com/projectriff/go-function-invoker)
- [ ] Ruby (see #226)
- [ ] [Rust](https://github.com/projectriff/rust-function-invoker)
- [ ] c# on .Net core

### Extensibility
- [ ] Bring your own invoker #1093

### Build
- [ ] Function builds using buildpacks #654

### Protocols
- [x] HTTP
- [ ] gRPC
- [ ] [rSocket](http://rsocket.io/)

### Semantics
- [x] sync, single event-at-a-time
- [ ] concurrent event-at-a-time - no shared state across events
- [ ] multi-event windowing with shared state for aggregation etc.
- [ ] async separation of input and output
- [ ] suspend/resume checkpoints a-la [Azure Durable Functions](https://github.com/Azure/azure-functions-durable-extension#durable-functions)

**Comment by ddieruf** [comment]
Is it possible to get an update on this roadmap? I am specifically interested in support for .NET core.

**Comment by scothis** [comment]
stale
